In [1]:
# Install libraries

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\vamsi\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vamsi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import libraries and load dataset

In [2]:
import pandas as pd

In [31]:
df=pd.read_excel("C:/Users/vamsi/Downloads/Heart disease project/heart_dataset_practice.xlsx")

In [32]:
df.head()

,age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,BP_level,chol_level,Heartrate_level,Stress_level,Slope_level,vessel_blockage
0,63,Male,Asymptomatic,145,233,High,Normal,150,No,2.3,0,0,Normal,Has heart disease,High,Borderline High,Average,High,Good,Normal
1,37,Male,Non anginal pain,130,250,Normal,Warning,187,No,3.5,0,0,Permanent Problem,Has heart disease,Elevated,High,Good,High,Good,Normal
2,41,Female,Atypical angina,130,204,Normal,Normal,172,No,1.4,2,0,Permanent Problem,Has heart disease,Elevated,Borderline High,Good,Moderate,High Risk,Normal
3,56,Male,Atypical angina,120,236,Normal,Warning,178,No,0.8,2,0,Permanent Problem,Has heart disease,Elevated,Borderline High,Good,Low,High Risk,Normal
4,57,Female,Typical angina,120,354,Normal,Warning,163,Yes,0.6,2,0,Permanent Problem,Has heart disease,Elevated,High,Good,Low,High Risk,Normal

In [33]:
# Understand dataset

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              303 non-null    int64
 1   Sex              303 non-null    object
 2   cp               303 non-null    object
 3   trestbps         303 non-null    int64
 4   chol             303 non-null    int64
 5   fbs              303 non-null    object
 6   restecg          303 non-null    object
 7   thalach          303 non-null    int64
 8   exang            303 non-null    object
 9   oldpeak          303 non-null    float64
 10  slope            303 non-null    int64
 11  ca               303 non-null    int64
 12  thal             303 non-null    object
 13  target           303 non-null    object
 14  BP_level         303 non-null    object
 15  chol_level       303 non-null    object
 16  Heartrate_level  303 non-null    object
 17  Stress_level     303 non-null    object
 18  Slope_level      303 non-null    object
 19  vessel_blockage  303 non-null    object
dtypes: float64(1), int64(6), object(13)
memory usage: 47.5+ KB

In [35]:
df.shape

(303, 20)

In [36]:
df.dtypes

age                  int64
Sex                 object
cp                  object
trestbps             int64
chol                 int64
fbs                 object
restecg             object
thalach              int64
exang               object
oldpeak            float64
slope                int64
ca                   int64
thal                object
target              object
BP_level            object
chol_level          object
Heartrate_level     object
Stress_level        object
Slope_level         object
vessel_blockage     object
dtype: object

In [37]:
# Statistics summary

In [38]:
df.describe()

,age,trestbps,chol,thalach,oldpeak,slope,ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,131.623762,246.264026,149.646865,1.039604,1.399340,0.729373
std,9.082101,17.538143,51.830751,22.905161,1.161075,0.616226,1.022606
min,29.000000,94.000000,126.000000,71.000000,0.000000,0.000000,0.000000
25%,47.500000,120.000000,211.000000,133.500000,0.000000,1.000000,0.000000
50%,55.000000,130.000000,240.000000,153.000000,0.800000,1.000000,0.000000
75%,61.000000,140.000000,274.500000,166.000000,1.600000,2.000000,1.000000
max,77.000000,200.000000,564.000000,202.000000,6.200000,2.000000,4.000000

In [39]:
# check null values

In [40]:
df.isnull().sum()

age                0
Sex                0
cp                 0
trestbps           0
chol               0
fbs                0
restecg            0
thalach            0
exang              0
oldpeak            0
slope              0
ca                 0
thal               0
target             0
BP_level           0
chol_level         0
Heartrate_level    0
Stress_level       0
Slope_level        0
vessel_blockage    0
dtype: int64

In [41]:
# Note:- There is no null values in data

In [42]:
# check duplicates

In [43]:
df.duplicated().sum()

np.int64(1)

In [44]:
df[df.duplicated()]

,age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,BP_level,chol_level,Heartrate_level,Stress_level,Slope_level,vessel_blockage
164,38,Male,Non anginal pain,138,175,Normal,Warning,173,No,0.0,2,4,Permanent Problem,Has heart disease,Elevated,Normal,Good,Low,High Risk,Severe

In [45]:
df[df.duplicated(keep=False)]

,age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,BP_level,chol_level,Heartrate_level,Stress_level,Slope_level,vessel_blockage
163,38,Male,Non anginal pain,138,175,Normal,Warning,173,No,0.0,2,4,Permanent Problem,Has heart disease,Elevated,Normal,Good,Low,High Risk,Severe
164,38,Male,Non anginal pain,138,175,Normal,Warning,173,No,0.0,2,4,Permanent Problem,Has heart disease,Elevated,Normal,Good,Low,High Risk,Severe

In [46]:
# Remove duplicates

In [47]:
df=df.drop_duplicates()

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
# Reset index

In [50]:
df=df.reset_index()

In [51]:
# Change column names clearly

In [52]:
df=df.rename(columns={
'cp':'chest_pain_type',
'trestbps':'blood_pressure_while_resting',
'chol':'cholesterol_in_blood',
'fbs':'blood_sugar_while_fasting',
'restecg':'ECG_while_resting',
'thalach':'heart_rate_during_excercise',
'exang':'chest_pain_during_excercise',
'oldpeak':'heart_stress_during_excercise',
'slope':'heart_stress_during_peak_excercise',
'ca':'blood_vessels',
'thal':'blood_flow_in_heart',
'target':'heart_disease_patient'})

In [53]:
df.head()

,index,age,Sex,chest_pain_type,blood_pressure_while_resting,cholesterol_in_blood,blood_sugar_while_fasting,ECG_while_resting,heart_rate_during_excercise,chest_pain_during_excercise,...,heart_stress_during_peak_excercise,blood_vessels,blood_flow_in_heart,heart_disease_patient,BP_level,chol_level,Heartrate_level,Stress_level,Slope_level,vessel_blockage
0,0,63,Male,Asymptomatic,145,233,High,Normal,150,No,...,0,0,Normal,Has heart disease,High,Borderline High,Average,High,Good,Normal
1,1,37,Male,Non anginal pain,130,250,Normal,Warning,187,No,...,0,0,Permanent Problem,Has heart disease,Elevated,High,Good,High,Good,Normal
2,2,41,Female,Atypical angina,130,204,Normal,Normal,172,No,...,2,0,Permanent Problem,Has heart disease,Elevated,Borderline High,Good,Moderate,High Risk,Normal
3,3,56,Male,Atypical angina,120,236,Normal,Warning,178,No,...,2,0,Permanent Problem,Has heart disease,Elevated,Borderline High,Good,Low,High Risk,Normal
4,4,57,Female,Typical angina,120,354,Normal,Warning,163,Yes,...,2,0,Permanent Problem,Has heart disease,Elevated,High,Good,Low,High Risk,Normal

In [61]:
# EDA - exploratory data analysis

In [62]:
# Check unique values

In [63]:
df['Sex'].value_counts()
df['chest_pain_type'].value_counts()

chest_pain_type
Typical angina      143
Non anginal pain     86
Atypical angina      50
Asymptomatic         23
Name: count, dtype: int64

In [71]:
# Filtering rows

In [70]:
df[df['age'] > 50]
df[df['cholesterol_in_blood'] > 200]

,index,age,Sex,chest_pain_type,blood_pressure_while_resting,cholesterol_in_blood,blood_sugar_while_fasting,ECG_while_resting,heart_rate_during_excercise,chest_pain_during_excercise,...,heart_stress_during_peak_excercise,blood_vessels,blood_flow_in_heart,heart_disease_patient,BP_level,chol_level,Heartrate_level,Stress_level,Slope_level,vessel_blockage
0,0,63,Male,Asymptomatic,145,233,High,Normal,150,No,...,0,0,Normal,Has heart disease,High,Borderline High,Average,High,Good,Normal
1,1,37,Male,Non anginal pain,130,250,Normal,Warning,187,No,...,0,0,Permanent Problem,Has heart disease,Elevated,High,Good,High,Good,Normal
2,2,41,Female,Atypical angina,130,204,Normal,Normal,172,No,...,2,0,Permanent Problem,Has heart disease,Elevated,Borderline High,Good,Moderate,High Risk,Normal
3,3,56,Male,Atypical angina,120,236,Normal,Warning,178,No,...,2,0,Permanent Problem,Has heart disease,Elevated,Borderline High,Good,Low,High Risk,Normal
4,4,57,Female,Typical angina,120,354,Normal,Warning,163,Yes,...,2,0,Permanent Problem,Has heart disease,Elevated,High,Good,Low,High Risk,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,292,58,Female,Typical angina,170,225,High,Normal,146,Yes,...,1,2,Normal,No heart disease,High,Borderline High,Average,High,Risk,Moderate
292,293,67,Male,Non anginal pain,152,212,Normal,Normal,150,No,...,1,0,Temporary problem,No heart disease,High,Borderline High,Average,Low,Risk,Normal
297,298,57,Female,Typical angina,140,241,Normal,Warning,123,Yes,...,1,0,Temporary problem,No heart disease,High,High,Average,Low,Risk,Normal
298,299,45,Male,Asymptomatic,110,264,Normal,Warning,132,No,...,1,0,Temporary problem,No heart disease,Normal,High,Average,Moderate,Risk,Normal
301,302,57,Female,Atypical angina,130,236,Normal,Normal,174,No,...,1,1,Permanent Problem,No heart disease,Elevated,Borderline High,Good,Low,Risk,Moderate

In [90]:
df.groupby('heart_disease_patient')['Sex'].count()

heart_disease_patient
Has heart disease    164
No heart disease     138
Name: Sex, dtype: int64

In [79]:
df.groupby('Sex')['cholesterol_in_blood'].count()

Sex
Female     96
Male      206
Name: cholesterol_in_blood, dtype: int64

In [91]:
# Save cleaned data

In [92]:
df.to_excel("C:/Users/vamsi/Downloads/Heart disease project/heart_dataset_practice.xlsx",index=False)